ZEISS-PiWeb/PiWeb-Api

src/Common/Data/RestClientHelper.cs

- check if there are requested attributes first
- adds None definition only if no specific attributes are requested
- see [https://github.com/ZEISS-PiWeb/PiWeb-Api/issues/10](https://github.com/ZEISS-PiWeb/PiWeb-Api/issues/10)

[PIWEB-10842] fix: Swap conditions

---

build.cake
src/Api.csproj
src/Common/Utilities/OAuthHelper.cs
src/app.config
src/packages.config

System.IdentityModel.Tokens.Jwt 5.x is not binary compatible with System.IdentityModel.Tokens.Jwt 4.x. Therefore any projekt that has already updated this very nuget for other reasons cannot consume PiWeb API SDK anymore.

update nuget System.IdentityModel.Tokens.Jwt to current major version

---

build.cake

Now all NuGets use the same GitVersion. This way all dependencies refer to the NuGets of one AppVeyor-Build. Updating Api.Rest automatically updates Defintions and Dtos.

feat: Use GitVersion for all NuGets

---

src/Api.Definitions/Api.Definitions.csproj
src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
src/Api.Rest.Dtos/RawData/RawDataArchiveBulkQueryDto.cs
src/Api.Rest.Dtos/RawData/RawDataArchiveContentDto.cs
src/Api.Rest.Dtos/RawData/RawDataArchiveEntriesDto.cs
src/Api.Rest.Dtos/RawData/RawDataArchiveIndexDto.cs
src/Api.Rest.Dtos/RawData/RawDataArchiveSelectorDto.cs
src/Api.Rest.Dtos/RawData/RawDataBulkQueryDto.cs
src/Api.Rest.Dtos/RawData/RawDataSelectorDto.cs
src/Api.Rest/Api.Rest.csproj
src/Api.Rest/Contracts/IRawDataServiceRestClientBase.cs
src/Api.Rest/Contracts/RawDataServiceFeatureMatrix.cs
src/Api.Rest/HttpClient/RawData/RawDataServiceRestClient.cs

This PR adds methods for retrieving information about archive entries as well as requested files of specified archives. This functionality expects that specified raw data is an archive of known format, currently .zip files.
New methods in RawDataServiceRest:
GetRawDataArchiveEntries - get a list of entries of specified archive
GetRawDataArchiveContent - get specified file of archive as byte stream
RawDataArchiveEntryQuery - get multiple lists of entries for queried archives
RawDataArchiveContentQuery - get multiple files of queried archives in BSON format

PIWEB-2881: Add archive lookup for archives saved as raw data

---

src/Api.Rest.Dtos.Tests/Api.Rest.Dtos.Tests.csproj
src/Api.Rest.Dtos.Tests/Data/OrderDtoParserTests.cs
src/Api.Rest.Dtos/Data/AbstractMeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/DistinctMeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/OrderDtoParser.cs
src/Api.sln

Within this PR, the method `AbstractMeasurementFilterAttributesDto.ParseOrderBy` was extracted into the separate class `OrderDtoParser`.
I also wrote some unit tests for the new class.

Parse OrderDTO extracted into a separate class

---

src/Api.Rest.Dtos/Data/AbstractMeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs

The query parameters where validated against the current PiWeb swagger documentation

Fix: Correct notation (Camel Case) for query parameters related to measurements

---

_pages/SDK/v6.0/021-general.md
_pages/SDK/v6.0/022-basics/0221-basics-configuration.md
_pages/SDK/v6.0/022-basics/0222-basics-inspectionplan.md
_pages/SDK/v6.0/022-basics/0223-basics-measurementsandvalues.md
_pages/SDK/v6.0/022-basics/0224-basics-rawdata.md

- fixes for compilation: variable names, missing semicolons, brackets
- "client" was changed to "DataServiceClient", according to the other examples and the initial declaration
- two examples were swapped to create entities before fetching them

docs: fixed sdk examples

---

_pages/API/v1.5/DataService/025-dataservice-inspectionplan.md
_pages/SDK/v6.0/022-basics/0222-basics-inspectionplan.md

Clearify how to create versioning entries to avoid the misunderstanding that PiWeb Server creates versioning comments when using the API.

Extend documentation for versioning

---

build.cake

Fixed a mismatch of dependencies between .csproj-files and the build.cake.
Set version of GitVersion.CommandLine to 5.5.0, since there seems to be a bug in latest release.

Fix: Dependency in build.cake

---

src/Api.Rest.Dtos/Data/OperationExecutionStatusDto.cs
src/Api.Rest.Dtos/Data/OperationStatusDto.cs
src/Api.Rest/Common/Client/RestClientBase.cs
src/Api.Rest/Contracts/DataServiceFeatureMatrix.cs
src/Api.Rest/Contracts/WrappedServerErrorException.cs
src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs

The DataService methods
- DeleteMeasurementsByUuid
- DeleteMeasurementsByPartUuids
- DeleteMeasurementsByPartPath
will automatically use an async pattern with polling if the server supports this feature.
This way the awaitable task is independent of the HTTP timeout.

[PIWEB-13767] feat: Add async deletion of measurements

---

src/Api.Rest.Dtos.Tests/PathHelperTests.cs
src/Api.Rest.Dtos/PathHelper.cs

There are some behaviour changes when comparing strings between .NET CORE and .NET 5. It leads to unwanted behaviours when a project using .NET 5 references PiWeb Api.  
https://docs.microsoft.com/de-de/dotnet/standard/base-types/string-comparison-net-5-plus

fix: Make string comparison independent of the cultures

---

src/Api.Rest.Dtos/Data/CatalogAttributeDefinitionDto.cs

AttributeDefinitionDto already has one, so this seemed inconsistent, as mentionend in #82.

feat: Add constructor to CatalogAttributeDefinitionDto

---

src/Api.Rest/Common/Utilities/CertificateHelper.cs

If a certificate has a duplicate in the certificate store we simply return the first occurence. Thumbprint is unique for the secure hash functions currently used in certificate infrastructure, so the returned certificates are exactly the same.

Fix: Return first certificate for thumbrint search of certificates

---

src/Api.Rest.Dtos/Data/SearchConditionParser.cs
src/Api.Rest.Tests/Dtos/Data/SearchConditionParserTest.cs

- use smarter detection of closing bracket for condition values to avoid detecting brackets used as actual values
- add tests for SearchConditionParser
Per definition the closing bracket of a search condition is either followed by + for concatenation or by an end of string. We now match this using regex instead of simply searching for the next closing bracket. This way the parser can handle closing brackets inside the values, e.g. 123In[[1,2,3];[4,5,6],[7,8,9]] without breaking compatibility.

[PIWEB-14185] fix: Adapt detection of closing brackets in SearchConditionParser

---

src/Api.Rest.Tests/HttpClient/Data/DataServiceRestClientTest.cs
src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs

Issue: #93 
Consider LimitResult and OrderBy when combining results of multiple queries which are part of one request which wa split due to URI length restriction.
Situation: Request measurements for many parts. Since the URI would get too long we split the request into multiple ones using the same filter criterias, e.g LimtResult=20. Each request will yield 20 measurements in correct order. Until now the results were simply combined into one array, which resultetd in 60 measurements instead of 20 and the order was not correct.
Fix: In the case of splitting a request we now evaluate the limit and sort the result according to requested order.

Fix: LimitResult and OrderBy when splitting request

---

src/Api.Rest/Common/Client/RestClientBase.cs
src/Api.Rest/Common/Client/TimeoutHandler.cs

This PR fixes a bug where a `TimeoutException` is thrown in cases there was no timeout. 
This happened due to the reason there was no built-in way to recognize whether a request was canceled due to timeout or a normal cancellation. There was a workaround checking the passed `CancellationToken` which worked in most cases, but did not work if the `HttpClient` was disposed with pending requests. But in `.NET 5.0` Microsoft finally added a way to recognize the timeout by checking the inner exception for being a `TimeoutException`. This fix was used as base for fixing the issue by using a custom `HttpMessageHandler` which does now handle the timeout instead of the `HttpClient` itself.
details can be found here:
https://github.com/dotnet/runtime/issues/21965 …

[PIWEB-14814] fix: Correctly throw TimeoutException on timeout only

---

src/Api.Rest.Dtos/Data/AbstractMeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/DistinctMeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs
src/Api.Rest/Contracts/DataServiceFeatureMatrix.cs
src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs

New parameter for measurement search: LimitResultPerPart.
- in combination with a part path and deep this will trigger a search for all child parts and return the specified amount of measurements per part
- in combination with a list of part uuids this will return the specified amount of measurements per part uuid

Add parameter LimitResultPerPart to filter classes

---

src/Api.Rest/Common/Client/RestClientBase.cs
src/Api.Rest/Common/Client/TimeoutHandler.cs

This PR prevents a potential deadlock when invoking requests from synchronous contexts. It also ensures now that the internal `HttpClient` timeout is set infinite.

[PIWEB-14814] fix: Fix potential deadlocking

---

_pages/API/01-general.md

Since PiWeb 7.8 the string encoding defaults to UTF-8. In lower versions this depends on the machine running PiWeb Server.

Add encoding information to General Information

---

src/Api.Rest.Tests/Contracts/FeatureMatrixTest.cs
src/Api.Rest/Contracts/FeatureMatrix.cs

This PR fixes a bug where the reason for a ServerApiNotSupportedException was switched by accident when creating an ServerApiNotSupportedException in class FeatureMatrix.

fix creation of ServerApiNotSupportedException in FeatureMatrix

---

build.cake
src/Api.Rest/Api.Rest.csproj
src/Api.Rest/Common/Client/FilesystemCacheStore.cs
src/Api.Rest/Common/Client/RestClientBase.cs

Enables caching for .Net Core, using the "CacheCow". This PR also includes a simple `FilesystemCacheStore`, since CacheCow only provides an `InMemoryCacheStore`.

fix: caching for .net core

---

src/Api.Definitions/Api.Definitions.csproj
src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
src/Api.Rest/Api.Rest.csproj
src/Api.Rest/Common/Client/RestClientBase.cs

This PR adds support for the PiWeb-Api being used from within the browser using web assembly by disabling all options that are not supported directly in browsers.
Additionally there is now support for passing an optional HTTP message handler into the REST client object to gain access to the message object for each request for handling built-in features which was not possible before.
[See also](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/call-web-api.md#httpclient-and-httprequestmessage-with-fetch-api-request-options-2)

feat: Make PiWeb-Api to support also being used in browser (WASM)

---

src/Api.Rest.Dtos.Tests/Data/AttributeDtoExtensionsTest.cs
src/Api.Rest.Dtos.Tests/Data/AttributeDtoTest.cs
src/Api.Rest.Dtos/Data/AttributeDto.cs

Since the preventing raw value initialization with a string value causes some side effects, the change is reverted.

Revert preventing raw value initialization with a string value

---

src/Api.Rest/Contracts/IDataServiceRestClientBase.cs
src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs

- catalog entry key is of datatype short, not int, see issue #6
- also renamed it to key since this is the term used in CatalogEntryDto

Change parameter data type in CheckCatalogEntryUsage

---

.github/workflows/build-and-pack.yml
.github/workflows/create-release.yml
.github/workflows/develop.yml
.github/workflows/feature-branch.yml
.github/workflows/gitversion.yml
.github/workflows/publish.yml
src/Api.Definitions/Api.Definitions.csproj
src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
src/Api.Rest/Api.Rest.csproj

This PR adds different workflows using GitHub Actions.
Workflows:
- Build, test and pack PRs to develop branch
- Publish alpha package to GitHub feed on push to develop (aka merging a PR)
- GitVersion computes correct version for nuget
- Create-Release workflow to automatically create a release and publish it to nuget.org
- Adds RepositoryUrl to .csproj since it is needed for the GitHub nuget feed
Further TODOs:
- #170
- #171

Add GitHub actions for different workflows

---

src/Api.Rest.Dtos/Data/DataMeasurementDto.cs

The list of characteristic values in `DataMeasurementDto` should not return `null` like in previous versions.

List of characteristic values in DataMeasurementDto should not be null

---

.github/workflows/build-and-pack.yml
.github/workflows/gitversion.yml
BUILDING.md
README.md
src/Api.Definitions/Api.Definitions.csproj
src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
src/Api.Rest/Api.Rest.csproj

- Update BUILDING.md and status badge in README.md
- Do not include .pdb files in the NuGet to reduce file size again (the same as before GitHub Actions, we do have a task for adding SourceLink later)
- Remove retry-rumber from version, since retry does not change source code, thus creating the same nuget
- Pushes to PR or force pushing creates a new workflow run, increrasing the run-number instead to ensure different versions

Update build and build doc

---

src/Api.Definitions/Api.Definitions.csproj

- release workflow automatically raises the version and commits the changes
- no changes to commit will lead to an error
- we simply lower one version to have at least one change when creating the release via workflow

fix: Lower version to fix problem in release action

---

src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs

Get rid of Task.WhenAll() by parallelizing request execution when retrieving measurements

Parallelize request execution when retrieving measurements

---

src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs

Previously, the variable _result.Length_ was the number of executed tasks (so the number of splits by uuid). Now it is the actual length of the result list of measurements. The method LimitAndSortResult needs the number of parallel executions, since it only needs to limit and sort again if splitting has happened. Otherwise it uses a fast path to just return the result, since it is already limited and sorted by the server.

fix: Use correct value as parameter for LimitAndSortResult

---

src/Api.Rest.Dtos/Data/MeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs

- case sensitivity is now optional in parse method of filter classes
- fixed line breaks

refactor: make case sensitivity optional in parse method

---

src/Api.Core/Attribute.cs
src/Api.Rest.Dtos.Tests/Data/AttributeTest.cs

This pull request improves the comparison of attributes in the situation one attribute was created from a string and the other from a double. The string attribute with a value of for example "0.1" is now parsed to double before comparison so that the transient value of 0.10000000000000001 is used in the equals method. Before the fix the string values had been compared (for example "0.1" with "0.10000000000000001") which had failed.

Fix comparison of double attributes

---

_pages/API/01-general.md
_pages/SDK/v8.2/022-basics/0225-basics-security.md

- add missing authentication methods to General Information page
- add example for certificate authentication to .NET SDK doc

doc: Extend security documentation

---

src/Api.Rest/Common/Authentication/IAuthenticationHandler.cs
src/Api.Rest/Common/Authentication/IInitializationContext.cs
src/Api.Rest/Common/Authentication/IRequestContext.cs
src/Api.Rest/Common/Authentication/IResponseContext.cs
src/Api.Rest/Common/Authentication/InitializationContext.cs
src/Api.Rest/Common/Authentication/NonInteractiveAuthenticationHandler.cs
src/Api.Rest/Common/Authentication/RequestContext.cs
src/Api.Rest/Common/Authentication/ResponseContext.cs
src/Api.Rest/Common/Client/RestClient.cs
src/Api.Rest/Common/Client/RestClientBase.cs
src/Api.Rest/Contracts/ICustomRestClient.cs
src/Api.Rest/Contracts/IDataServiceRestClientBase.cs
src/Api.Rest/Contracts/IRawDataServiceRestClientBase.cs
src/Api.Rest/Contracts/RefreshPolicy.cs
src/Api.Rest/HttpClient/Builder/IRestClientBuilder.cs
src/Api.Rest/HttpClient/Builder/RestClientBuilder.cs
src/Api.Rest/HttpClient/Builder/RestClientSettings.cs
src/Api.Rest/HttpClient/Builder/StandardTimeoutType.cs
src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
src/Api.Rest/HttpClient/OAuth/IOAuthServiceRestClient.cs
src/Api.Rest/HttpClient/OAuth/OAuthServiceRestClient.cs
src/Api.Rest/HttpClient/RawData/RawDataServiceRestClient.cs

This PR aims to improve the necessary code complexity for integrating the PiWeb-API in an import plugin. The major problem of the current PiWeb-API state is setting up non-interactive OAuth/OIDC authentication for a provided refresh token. Currently this requires deriving several classes to gain access to protected constructors, overriding protected methods and also manually implementing the OAuth/OIDC flow to gain access tokens.
There are also several minor obstacles that raise the necessary code complexity:
- Rest client constructors have too many parameters and need to be set up individually.
- Endpoint names are not public but required when deriving from rest clients leading to duplication of constants
The solutions I chose to implement are supposed to improve these problems not only …

Improve creation of rest clients

---

.github/workflows/deploy-gh-pages.yml

Uses action from https://github.com/ZEISS-PiWeb/github-actions/pull/35 to build and deploy the API documentation using GitHub Pages.

feat: Use action to build and deploy Github Pages

---

src/Api.Rest.Dtos/Data/ServiceInformationDto.cs
src/Api.Rest.Dtos/RawData/ServiceInformationDto.cs

This PR adds a extended version property to the service information returned by the PiWeb server which consists of Version-BuildDate-BuildHash.

feat: Add extended version property

---

.github/workflows/create-release.yml
.github/workflows/create-service-pack.yml
.github/workflows/develop.yml
.github/workflows/feature-branch.yml
src/Api.Core/Api.Core.csproj
src/Api.Definitions/Api.Definitions.csproj
src/Api.Rest.Dtos.Tests/Api.Rest.Dtos.Tests.csproj
src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
src/Api.Rest.Tests/Api.Rest.Tests.csproj
src/Api.Rest/Api.Rest.csproj

**Update target frameworks:**
- remove .NET 7
- add .NET 8
**Update dependencies:**
_Api.Definitions:_
- JetBrains.Annotations from 2020.3.0 to 2024.2.0
_Api.Core:_
- JetBrains.Annotations from 2020.3.0 to 2024.2.0
- Microsoft.Extensions.ObjectPool from 7.0.8 to 8.0.8
- CommunityToolkit.HighPerformance 8.2.0 to 8.3.0
_Api.Rest.Dtos:_
- JetBrains.Annotations from 2020.3.0 to 2024.2.0
- System.Text.Json from 7.0.3 to 8.0.4
- SauceControl.InheritDoc 1.3.0 to 1.4.0
_Api.Rest:_
- JetBrains.Annotations from 2020.3.0 to 2024.2.0
- CacheCow.Client from 2.12.1 to 2.13.1
- IdentityModel from 6.2.0 to 7.0.0
- Microsoft.IdentityModel.Logging from 6.34.0 to 8.0.2
- Microsoft.IdentityModel.Tokens from 6.34.0 to 8.0.2
- System.Text.Json from 7.0.3 to 8.0.4
- System.IdentityModel.Tokens.Jwt from 6.34.0 …

(MAJOR) feat: Update target framework and dependencies

---

src/Api.Rest/Api.Rest.csproj

Last PR #246  did not update the IdentityModel correctly. Fixed this.

feat: Update IdentityModel to 7.0.0

---

src/Api.Core/PathHelper.cs
src/Api.Rest.Dtos.Tests/PathHelperTests.cs

This PR improves recognition of delimiters at the end of paths which fixes a bug that occurred when creating and fetching a part which ended with a backslash.

fix: Recognize backslash at end of path as part of name

---

src/Api.Rest.Dtos/Data/MeasurementFilterAttributesDto.cs
src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs

- AllAttributeSelectionDto.False works correctly now
- will lead to the REST parameter being set to {}, meaning no attributes should be returned
Closes #252

[#252] fix: Measurement search with AllAttributeSelectionDto.False still returns attributes

---

_pages/API/1.11/DataService/023-dataservice-configuration.md

This PR extends the documentation for the ```CheckAttributeUsage``` endpoint with an explanation for the new behavior regarding wrapping the attribute value in quotation marks.

fix: Extended documentation for the CheckAttributeUsage endpoint

---

_pages/API/01-general.md
_pages/API/1.10/DataService/02-dataservice.md
_pages/API/1.11/DataService/02-dataservice.md
_pages/API/1.11/DataService/020-dataservice-releasenotes.md
_pages/API/1.11/DataService/021-dataservice-interfaceinformation.md
_pages/API/1.11/DataService/025-dataservice-inspectionplan.md
_pages/API/1.11/DataService/027-dataservice-measurementsandvalues-primarymeasurementkey.md
_pages/API/1.11/DataService/028-dataservice-events.md
_pages/API/v1.8/RawDataService/03-rawdataservice.md
_pages/API/v1.8/RawDataService/030-rawdataservice-releasenotes.md
_pages/API/v1.8/RawDataService/031-rawdataservice-interfaceinformation.md
_pages/API/v1.8/RawDataService/036-rawdataservice-events.md
_pages/SDK/v8.3/02-netsdk.md
_pages/SDK/v9.0/02-netsdk.md

This PR updates the documentation to the most recent version of the PiWeb API and its NuGet.
Changes:
1st commit: Update current versions
- update current versions of pages
2nd commit: Add new feature documentation
- add count endpoints for parts and characteristics
- add events to DataServiceRest page
- add events to RawDataServiceRest page
- update release notes
3rd commit: Fix small issues
- add information for history comment on inspection plan updates
- fix wrong max value for depth
- fix typos

Doc: Update documentation for 9.0.0 release

---

src/Api.Rest/Common/Utilities/OAuthHelper.cs
src/Api.Rest/HttpClient/OAuth/AccessTokenType.cs
src/Api.Rest/HttpClient/OAuth/AuthenticationFlows/AuthorizationCodeFlow.cs
src/Api.Rest/HttpClient/OAuth/AuthenticationFlows/HybridFlow.cs
src/Api.Rest/HttpClient/OAuth/AuthenticationFlows/OidcAuthenticationFlowBase.cs
src/Api.Rest/HttpClient/OAuth/OAuthConfiguration.cs

Commit 1 - fix: Automatically choose suitable JWT token as AccessToken
- use ID token as fallback if AccessToken is no JWT
- allow configuration from the server to enforce certain token type
- select the expiration time from the chosen token, in case times differ between ID and AccessToken
Commit 2 - fix: Throw error on problems during OIDC login
- do not silently accept error states of the authentication procedure but throw an exception instead
- this way the user can better understand why the login failed (e.g. invalid configuration for OIDC)
- only throw during manual login, but not on refresh (to allow for simply logging in again if refresh fails, an exception would not bring up the login dialog)

Fix: automatically choose access token type

---

src/Api.Core/Api.Core.csproj
src/Api.Definitions/Api.Definitions.csproj
src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
src/Api.Rest/Api.Rest.csproj

This PR adds SPDX license information to the .csproj files.
Hopefully, this will result in Blackduck and other FOSS tools can detect the license from PiWeb API nugets automatically.

feat: add SPDX license information to .csproj files

---

src/Api.Rest/HttpClient/OAuth/AuthenticationFlows/OidcAuthenticationFlowBase.cs

- expiration time was not extracted for token selection modes other than auto, meaning all token would be expired due to DateTime default
- for OIDC ID Token we extract it from the token itself (as done in the auto case)
- for OAuth Access Token we use the expiration from the token request (as done in the auto case)

Fix: Token expiration time extraction

---

src/Api.Rest/Common/Client/RestClient.cs
src/Api.Rest/Common/Client/RestClientBase.cs
src/Api.Rest/Common/Client/TimeoutHandler.cs
src/Api.Rest/HttpClient/Builder/RestClientBuilder.cs

Makes the RestClient constructor taking a settings object public so that custom rest clients based on RestClient can be implemented by API users.

Public RestClient Constructor

---

src/Api.Rest/HttpClient/OAuth/OAuthTokenInformation.cs

- allows for easy separation of client registrations at the ID Provider, one for native desktop clients and one for browser apps

fix: Add additional OIDC ClientID for PiWeb browser apps

---

src/Api.Rest/HttpClient/OAuth/OAuthTokenInformation.cs

- allows for easy separation of client registrations at the ID Provider

fix: Add additional OIDC ClientID for PiWeb browser apps in compatibility mode

---

src/Api.Rest/HttpClient/OAuth/IOAuthServiceRestClient.cs

- old doc stated that the call to InterfaceInformation _does_ produce a lot of work
- fix this by using the same wording as in the other clients

fix: Mistake in OAuthService code doc

---

_pages/API/v1.8/RawDataService/034-rawdataservice-rawdataobjects.md
_pages/SDK/v9.1/022-basics/0220-basics-create.md

- add new way of creating the RestClients using the RestClientBuilder
- add using statement and hint that the RestClients implement IDisposable
- describe how to use encoded-word syntax for sending non-ASCII characters in the Content-Disposition header

doc: Add RestClientBuilder and filename encoding to documentation
