- .gitignore
- src/Api.csproj
- src/Api.sln.DotSettings
- src/Common/Utilities/CredentialRepository.cs
- src/Common/Utilities/OAuthHelper.cs
- src/Common/Utilities/OAuthTokenCredential.cs
- src/Common/Utilities/ProtocolHelperExtensions.cs
- tests/Api.Tests.csproj
- tests/Common/Utilities/CredentialRepositoryTests.cs
- Restored the OAuthHelper class which is part of the public API
- Move credential caching into new class and add tests
- Fixed that credentials stored by URL where not be recovered, correctly.
> feat: Restore and improve OAuthHelper

- _pages/SDK/v6.0/023-migration.md
Add steps required to migrate from version 5.0 to 6.0
> Migration guide to version 6.0

- src/Api.Rest/Contracts/IRawDataServiceRestClientBase.cs
- src/Api.Rest/HttpClient/RawData/RawDataServiceRestClient.cs
Add method overload for RawDataArchiveEntryQuery which expects array of RawDataInformation
> feat: Add convenience method for archive query

- src/Api.Rest/Common/Data/FilterString/Formatter/FilterTreeFormatter.cs
Fix missing case for TokenType.Null
> Fix missing case for TokenType.Null

- src/Api.Definitions/WellKnownKeys.cs
- src/Api.Rest/Common/Client/ICacheClearable.cs
- src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
some documentation corrections
> docs: doc comments corrected

- _pages/API/01-general.md
HTTP status codes "Method Not Allowed" and "Unsupported Media Type" can occur.
> fix: added http status codes 405, 415

- src/Api.Rest.Dtos.Tests/Api.Rest.Dtos.Tests.csproj
- src/Api.Rest.Tests/Api.Rest.Tests.csproj
- src/Api.Rest/Api.Rest.csproj
- src/Api.Rest/Common/Utilities/OAuthHelper.cs
This PR mainly updates referenced nuget packages. In case of the package *IdentityModel*, I've made necessary modifications due to the fact that IdentityModel4 contains breaking changes when upgrading from IdentityModel2.
> Update IdentityModel2 to IdentityModel4

- src/Api.Rest/Common/Client/RestClientBase.cs
**Description**
This PR simply passes the `CancellationToken` of the http request to the virtual members of the rest client that are responsible for checking for complete authentication information on requests. 
**Scenario**
PiWeb uses those members to wire up showing a login dialog to the user if login information is needed. Currently it is not possible to cancel the request using the `CancellationToken` if the login dialog is shown in that moment, since the cancel information is not being passed down to the dialog.
> [PIWEB-13907] feat: Add cancellation support for requesting login information

- src/Api.Definitions/Api.Definitions.csproj
- src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
- src/Api.Rest/Api.Rest.csproj
#68 contained a breaking change, so next version should be 7.0.0
> chore: Bump version to next major due to breaking changes

- src/Api.Rest.Dtos/Data/AttributeDto.cs
- src/Api.Rest.Dtos/Data/CatalogCollectionDto.cs
- src/Api.Rest.Dtos/Data/CatalogDto.cs
- src/Api.Rest.Dtos/Data/CatalogEntryDto.cs
- src/Api.Rest.Dtos/Data/ConfigurationDto.cs
- src/Api.Rest.Dtos/Data/DataMeasurementDto.cs
- src/Api.Rest.Dtos/Data/InspectionPlanDtoBase.cs
- src/Api.Rest.Dtos/Data/PathInformationDto.cs
- src/Api.Rest.Dtos/Data/SimpleMeasurementDto.cs
- src/Api.Rest.Dtos/RestClientHelper.cs
Dieser PR dient dazu, unnötige Allokationen zu vermeiden.
> Avoid allocations

- _pages/SDK/v7.0/02-netsdk.md
- _pages/SDK/v7.0/021-general.md
- _pages/SDK/v7.0/022-basics.md
- _pages/SDK/v7.0/022-basics/0220-basics-create.md
- _pages/SDK/v7.0/022-basics/0221-basics-configuration.md
- _pages/SDK/v7.0/022-basics/0222-basics-inspectionplan.md
- _pages/SDK/v7.0/022-basics/0223-basics-measurementsandvalues.md
- _pages/SDK/v7.0/022-basics/0224-basics-rawdata.md
- _pages/SDK/v7.0/022-basics/0225-basics-security.md
- _pages/SDK/v7.0/022-basics/0226-basics-archivelookup.md
- _pages/SDK/v7.0/023-migration.md
Add the SDK doc for version 7.0 for completeness, since this is the current version.
> Chore: Add SDK documentation v7.0

- src/Api.Rest.Dtos.Tests/Data/PathInformationExtensionTests.cs
Wrong separator in path to create test data.
> fix: Fix path to create tests data

- build.cake
- src/Api.Definitions/Api.Definitions.csproj
- src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
- src/Api.Rest/Api.Rest.csproj
Add NET 5 as target framework for more compatibility.
> feat: Add net5.0 as target framework

- src/Api.Rest.Tests/Contracts/FeatureMatrixTest.cs
- src/Api.Rest/Contracts/FeatureMatrix.cs
- src/Api.Rest/Contracts/ServerApiNotSupportedException.cs
This PR extends the ServerApiNotSupportedException to contain the supported major versions that were used for the Api support check.
> feat: extend ServerApiNotSupportedException

- _pages/API/v1.6/RawDataService/03-rawdataservice.md
- _pages/API/v1.7/DataService/02-dataservice.md
- _pages/API/v1.7/DataService/024-dataservice-catalogs.md
- _pages/API/v1.7/DataService/025-dataservice-inspectionplan.md
- _pages/API/v1.7/DataService/026-dataservice-measurementsandvalues.md
- _pages/API/v1.7/RawDataService/03-rawdataservice.md
- _pages/API/v1.7/RawDataService/030-rawdataservice-releasenotes.md
- _pages/API/v1.8/DataService/02-dataservice.md
- _pages/API/v1.8/DataService/024-dataservice-catalogs.md
- _pages/API/v1.8/DataService/025-dataservice-inspectionplan.md
- _pages/API/v1.8/DataService/026-dataservice-measurementsandvalues.md
- _pages/SDK/v7.0/02-netsdk.md
- _pages/SDK/v7.1/02-netsdk.md
- Update DataServiceRest doc to version 1.8
- Update RawDataServiceRest doc to version 1.7
- Update C# Doc to 7.1
- minor fixes
> doc: Update documentation for next release

- src/Api.Rest/Common/Client/FilesystemCacheStore.cs
- src/Api.Rest/Common/Client/FilesystemVaryHeaderStore.cs
- src/Api.Rest/Common/Client/RestClientBase.cs
Disables the behavior that the cache depends on the accept header.
> fix: store vary header information

- _pages/API/v1.8/DataService/026-dataservice-measurementsandvalues.md
Add examples for multiple search conditions to the different measurement methods.
> doc: Add example for multiple search conditions

- build.cake
- src/Api.Rest.Dtos.Tests/Api.Rest.Dtos.Tests.csproj
- src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
- src/Api.Rest.Tests/Api.Rest.Tests.csproj
- src/Api.Rest/Api.Rest.csproj
Upgrade due to security issues.
> chore: Upgrade Newtonsoft.JSON to 13

- src/Api.Rest/HttpClient/RawData/RawDataServiceRestClient.cs
CreateRawDataInternal was missing some ConfigureAwaits which could lead to deadlocks in synchronous code.
> fix: Add missing ConfigureAwaits in RawDataServiceRestClient

- src/Api.Rest/Contracts/IRawDataServiceRestClientBase.cs
- src/Api.Rest/HttpClient/RawData/RawDataServiceRestClient.cs
Adds methods to read and write rawdata using streams instead of byte[].
> feat: read and write rawdata streams

- src/Api.Rest.Dtos/Converter/AttributeArrayConverter.cs
- src/Api.Rest.Dtos/Converter/DataCharacteristicConverter.cs
- src/Api.Rest.Dtos/Data/AbstractMeasurementFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/AttributeDto.cs
- src/Api.Rest.Dtos/Data/AttributeItemDtoExtensions.cs
- src/Api.Rest.Dtos/Data/AttributeSelectorDto.cs
- src/Api.Rest.Dtos/Data/CatalogDto.cs
- src/Api.Rest.Dtos/Data/CatalogEntryDto.cs
- src/Api.Rest.Dtos/Data/ConfigurationDto.cs
- src/Api.Rest.Dtos/Data/DataMeasurementDto.cs
- src/Api.Rest.Dtos/Data/DataValueDto.cs
- src/Api.Rest.Dtos/Data/DistinctMeasurementFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/FieldDefinitions.cs
- src/Api.Rest.Dtos/Data/GenericSearchConditionDto.cs
- src/Api.Rest.Dtos/Data/IAttributeItemDto.cs
- src/Api.Rest.Dtos/Data/InspectionPlanCharacteristicDto.cs
- src/Api.Rest.Dtos/Data/InspectionPlanDtoBase.cs
- src/Api.Rest.Dtos/Data/InspectionPlanPartDto.cs
- src/Api.Rest.Dtos/Data/MeasurementFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/PathInformationExtension.cs
- src/Api.Rest.Dtos/Data/SearchConditionParser.cs
- src/Api.Rest.Dtos/Data/ServiceInformationDto.cs
- src/Api.Rest.Dtos/Data/SimpleMeasurementDto.cs
- src/Api.Rest.Dtos/Data/SimpleMeasurementStatusDto.cs
- src/Api.Rest.Dtos/RestClientHelper.cs
- src/Api.Rest.Dtos/StringUuidTools.cs
- src/Api.Rest.Tests/Dtos/Data/SearchConditionParserTest.cs
- src/Api.Rest/Common/Data/RestClientHelper.cs
- src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
> refactor: Use readonly lists and collections instead of arrays to avoid allocations

- src/Api.Rest.Dtos.Tests/PathHelperTests.cs
Now with code coverage of 95%.
> chore: Add tests for PathHelper

- src/Api.Rest.Tests/HttpClient/Data/DataServiceRestClientTest.cs
- src/Api.Rest/Common/Client/RequestBuilder.cs
- src/Api.Rest/Common/Data/RestClientHelper.cs
- src/Api.Rest/Common/Utilities/ParameterSplitter.cs
- src/Api.Rest/Contracts/IDataServiceRestClientBase.cs
- src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
- src/Api.Rest/HttpClient/RawData/Filter/Conditions/FilterCondition.cs
This is a follow up PR for #145
> Use readonly lists and collections instead of arrays to avoid allocations

- src/Api.Rest.Dtos/Data/SimpleMeasurementDto.cs
* This simplifies usage of the class
> Bring back setter for Time property

- src/Api.Rest.Dtos.Tests/Data/AttributeDtoTest.cs
Add tests for AttributeDto, current coverage: 75%.
> chore: Add tests covering AttributeDto

- src/Api.Rest.Dtos.Tests/Data/AttributeTests.cs
- src/Api.Rest.Dtos/Data/AbstractMeasurementFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/AttributeDto.cs
- src/Api.Rest.Dtos/Data/ConfigurationDto.cs
- src/Api.Rest.Dtos/Data/DistinctMeasurementFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/MeasurementFilterAttributesDto.cs
- src/Api.Rest.Dtos/Data/MeasurementValueFilterAttributesDto.cs
This PR contains a few refinements after the recent refactorings.
> Refine refactoring

- src/Api.Rest.Dtos/Data/AttributeDto.cs
- src/Api.Rest.Dtos/Data/AttributeItemDtoExtensions.cs
> fix: Fix refactoring bugs

- src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
- src/Api.Rest.Dtos/Data/ConfigurationDto.cs
This PR fixes 2 bugs introduced by the latest refactoring.
> Fix refactoring bugs

- src/Api.Rest.Dtos.Tests/Data/AttributeDtoExtensionsTest.cs
- src/Api.Rest.Dtos.Tests/Data/AttributeDtoTest.cs
- src/Api.Rest.Dtos/Data/AttributeDto.cs
- src/Api.Rest.Dtos/Data/AttributeItemDtoExtensions.cs
Adds test cases covering attribute retrieval when raw value is a string or only value is set.
> Improve test coverage of attribute value retrieval

- src/Api.Rest.Dtos.Tests/Data/AttributeDtoExtensionsTest.cs
- src/Api.Rest.Dtos.Tests/Data/CatalogEntryDtoTest.cs
- src/Api.Rest.Dtos.Tests/Data/PathInformationExtensionTests.cs
- src/Api.Rest.Dtos/Data/CatalogEntryDto.cs
- src/Api.Rest.Dtos/Data/PathInformationExtension.cs
Adds tests to improve test coverage of CatalogEntryDto and PathInformationExtension.
> Improve test coverage of CatalogEntryDto and PathInformationExtension

- src/Api.Rest/Common/Utilities/OAuthHelper.cs
Previously the discovery info was requested up to 3 times for single method run. This could be reduced to a single call.
> refactor: Only request discovery info once

- src/Api.Rest/Common/Utilities/OAuthHelper.cs
This PR adds an option to ignore any locally cached OAuth token information when requesting new OAuth token information for a cloud database.
This option can be used to always prompt an interactive OAuth login screen to let the user choose which account is to be used for authentication, no matter whether there is any locally cached token for the given cloud database available.
The expected use case is that the user can set a different cloud user for the Auto Importer service than he/she usually uses in the other client applications for that database URL without effecting the local cache, since the cache is shared between all client applications.
_I added XML comments at several places, feel free to suggest alternative wordings etc._
Related PiWeb issue: …
> [PIWEB-14953] feat: Add option to ignore local OAuth token cache

- _pages/SDK/v7.2/02-netsdk.md
- _pages/SDK/v7.2/021-general.md
- _pages/SDK/v7.2/022-basics.md
- _pages/SDK/v7.2/022-basics/0220-basics-create.md
- _pages/SDK/v7.2/022-basics/0221-basics-configuration.md
- _pages/SDK/v7.2/022-basics/0222-basics-inspectionplan.md
- _pages/SDK/v7.2/022-basics/0223-basics-measurementsandvalues.md
- _pages/SDK/v7.2/022-basics/0224-basics-rawdata.md
- _pages/SDK/v7.2/022-basics/0225-basics-security.md
- _pages/SDK/v7.2/022-basics/0226-basics-archivelookup.md
- _pages/SDK/v7.2/023-migration.md
- _pages/SDK/v8.0/02-netsdk.md
- _pages/SDK/v8.0/021-general.md
- _pages/SDK/v8.0/022-basics.md
- _pages/SDK/v8.0/022-basics/0220-basics-create.md
- _pages/SDK/v8.0/022-basics/0221-basics-configuration.md
- _pages/SDK/v8.0/022-basics/0222-basics-inspectionplan.md
- _pages/SDK/v8.0/022-basics/0223-basics-measurementsandvalues.md
- _pages/SDK/v8.0/022-basics/0224-basics-rawdata.md
- _pages/SDK/v8.0/022-basics/0225-basics-security.md
- _pages/SDK/v8.0/022-basics/0226-basics-archivelookup.md
- _pages/SDK/v8.0/023-migration.md
- adds version for 7.2
- adds placeholder for 8.0
Merged without review since no new texts etc.
> chore: Add missing nuget doc versions

- src/Api.Rest/Contracts/DataServiceFeatureMatrix.cs
- src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
Throw exception if case sensitivity is requested but not supported on server side.
> chore: Add version check for cases sensitivity feature

- src/Api.Rest/HttpClient/Data/DataServiceRestClient.cs
fix: NRE on emtpy measurement filter
> fix: NRE on emtpy measurement filter

- _pages/API/v1.7/RawDataService/034-rawdataservice-rawdataobjects.md
- highlight that MD5 is optional for POST/PUT
- add reminder to use compound uuid when sending raw data for measured values
> doc: Small improvements for RawData doc

- .github/workflows/create-release.yml
- .github/workflows/create-service-pack.yml
- .github/workflows/develop.yml
- .github/workflows/feature-branch.yml
- src/Api.Core/Api.Core.csproj
- src/Api.Definitions/Api.Definitions.csproj
- src/Api.Rest.Dtos.Tests/Api.Rest.Dtos.Tests.csproj
- src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
- src/Api.Rest.Tests/Api.Rest.Tests.csproj
- src/Api.Rest/Api.Rest.csproj
- updated most dependencies to the newest versions
- added .NET 7 as target framework (6 stays since it is a LTS release)
> Chore: Update Dependencies

- src/Api.Rest/Common/Client/RequestBuilder.cs
A function created by CreateWithAttachment (which is used as callback when sending a request later) can be called two times if authentication was missed during the first request. In this case the stream will not be reset to the original position. This PR fixes the bug where the content was empty for the second call.
> fix: multiple request attempts with same stream

- src/Api.Rest/Common/Client/RequestBuilder.cs
This PR reallows creating an attachment using a non-seekable stream for most common use cases. Only the special case of non-seekable streams in combination with a second request attempt (because of missing authentication settings) will fail.
> fix: reallow non-seeakable streams for common use case

- src/Api.Rest/Common/Utilities/CredentialRepository.cs
- token file is encrypted for the user and machine, so copying the file won't work on another machine or user
- simply ignore decryption exceptions and discard the file, to allow the user to sign in again
- the invalid file is overwritten afterwards with the correct login automatically
Hint for the reviewer: the main change is the relocation of decryption to the new method `TryDecryptData`. The other changes are mainly because I inverted the `if`-block to reduce nesting and lower code compelxity.
> fix: Discard token file on decryption exception

- src/Api.Rest/Common/Client/CommonRestClientBase.cs
- src/Api.Rest/Common/Client/IRestClient.cs
- src/Api.Rest/Common/Client/RestClientBase.cs
- src/Api.Rest/HttpClient/Builder/RestClientBuilder.cs
- src/Api.Rest/HttpClient/Builder/RestClientSettings.cs
This PR adds support for checking the certificate revocation list but without enabling the check by default.
> feat: support optional certificate revocation list check

- _pages/API/01-general.md
Wrong version of RawDataService
> fix: Wrong link in General Information Page

- .github/workflows/create-service-pack.yml
- reuse workflow from main workflow repository
> feat: Update service pack pipeline

- .github/workflows/create-release.yml
- .github/workflows/create-service-pack.yml
- .github/workflows/develop.yml
- .github/workflows/feature-branch.yml
- src/Api.Core/Api.Core.csproj
- src/Api.Definitions/Api.Definitions.csproj
- src/Api.Rest.Dtos.Tests/Api.Rest.Dtos.Tests.csproj
- src/Api.Rest.Dtos/Api.Rest.Dtos.csproj
- src/Api.Rest.Tests/Api.Rest.Tests.csproj
- src/Api.Rest/Api.Rest.csproj
- remove .NET 6 (EOL)
- add current .NET 9
> feat: Update target frameworks

- _pages/SDK/v9.1/02-netsdk.md
- _pages/SDK/v9.1/021-general.md
- _pages/SDK/v9.1/022-basics.md
- _pages/SDK/v9.1/022-basics/0220-basics-create.md
- _pages/SDK/v9.1/022-basics/0221-basics-configuration.md
- _pages/SDK/v9.1/022-basics/0222-basics-inspectionplan.md
- _pages/SDK/v9.1/022-basics/0223-basics-measurementsandvalues.md
- _pages/SDK/v9.1/022-basics/0224-basics-rawdata.md
- _pages/SDK/v9.1/022-basics/0225-basics-security.md
- _pages/SDK/v9.1/022-basics/0226-basics-archivelookup.md
- _pages/SDK/v9.1/023-migration.md
- create files for new .NET SDK version 9.10
- just a copy of previous docs
- new text will be added in a separate PR to make review easier
> doc: Add pages for .NET SDK version 9.1.0

- _includes/endpointTab.html
- _pages/API/01-general.md
- update documentation for OIDC
- add information about oAuthConfiguration endpoint and its values
- adapt summary of necessary login steps to match current state with Authentication Code Flow
> doc: Update OIDC documentation
